### ISSUE TITLE
Chrome 41 support

### ISSUE THREAD

**Issue by AliaksandrKi** [dschnelldavis/angular2-json-schema-form#101]
0.5.0-alpha.2 of angular2-json-schema-form is the latest version which works in Chrome 41
0.5.0-alpha.8 cause 'Uncaught TypeError: undefined is not a function' type of error (but works well in Chrome 45 and newer)
Is there any chance to return support for the old Chrome versions? Problem that it's necessary for creating AdobeIllustrator plugin extensions (AI has built in chromium41 and has not been updated for a long time)

**Comment by dschnelldavis** [comment]
It looks like you can fix this by adding some polyfills.

I loaded Chromium v41 and got the error you described. Then, partly by following the advice from [this StackOverflow post](https://stackoverflow.com/questions/42238490/angular-2-typeerror-undefined-is-not-a-function-for-array-includes), I added the following lines to polyfills.ts:

```javascript
import 'core-js/es6/object';
import 'core-js/es6/array';
import 'core-js/es7/array';
```

After that, everything appeared to work fine again.

**Comment by AliaksandrKi** [comment]
It is works indeed, thank you.
