### ISSUE TITLE
array inside an object is misbehaving

### ISSUE THREAD

**Issue by nirgilboa** [dschnelldavis/angular2-json-schema-form#102]
1. Paste the schema below into the playground area (taken from fixed issue #64)
2. Click Add to plcInfos to add another array item
Actual: new item appears above the plcInfos object with undefined values, new item not in output json
Expected: new item appears below plcInfos object, with empty defaults, json output matches

3. Click on the 'x' to remove the first plcInfos items and the 'Add to plcInfos" button disappears.

![image](https://user-images.githubusercontent.com/17432317/31132573-c48f75f8-a865-11e7-9d45-dc324111db8d.png)

{
  "schema": {
    "type": "object",
    "properties": {
      "queue": {
        "type": "object",
        "properties": {
          "host": { "type": "string" },
          "name": { "type": "string" },
          "plcInfos": {
                  "type": "array",
                  "maxItems": 2,
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": { "type": "string" },
                      "host": { "type": "string" }
                    }
                  }
                }
        }
      }
    }
  }
}

**Comment by nirgilboa** [comment]
This seems to have been fixed in the latest commits. However, removing items (i.e. clicking on the 'x') is now not possible.

**Comment by nirgilboa** [comment]
Fixed by the latest commits - no longer occurs on the demo playground

**Comment by dschnelldavis** [comment]
Great. Thanks for the update.
