### ISSUE TITLE
Asterisk for required fields now missing for Bootstrap

### ISSUE THREAD

**Issue by Thorski** [dschnelldavis/angular2-json-schema-form#103]
Something must have changed recently.   The asterisk for text fields is not showing in Bootstrap.

Easily demonstrated in the playground of a new git clone (not the online playground, it works fine there):

The asterisk for first name will not show in Bootstrap framework, but will in Material framework:   
<pre>
{
  "schema": {
    "type": "object",
    "required":[
      "first_name"
    ],
    "properties": {
      "first_name": { "type": "string" },
    }
  }
}
</pre>

**Comment by Thorski** [comment]
I have found that this was broken by the fix for #95 

This fix as implemented actually makes the asterisk not appear for required fields in the Bootstrap
Framework.

The new template code:
`  [innerHTML]="options?.title">
  <strong *ngIf="options?.title && !options?.notitle && options?.required"
 class="text-danger">*</strong>
 </label>`
 
is wrong, as the <strong... /strong> will not be included in the web page due to the innerHTML for the label being set to the title.   This is easy to show in the playground (not the online one but one from a new git clone), just by adding required to any text field.  

The <strong class="text-danger">*</strong> needs to be part of the HTML.   It is done
for array items or field sets and other things by changing the title:
    this.options.title += ' <strong class="text-danger">*</strong>';

Maybe it could / should be done this way for other fields with titles?

**Comment by Thorski** [comment]
I have fixed this by  removing the <strong... /strong> completely from the template,  and 
adding this code prior to the switch for layout type (it implements the template logic from the strong *ngIf):
<pre>
      if (this.options.title && this.layoutNode.type !=- 'tab' &&
          !this.options.notitle && this.options.required  &&
          this.options.title.indexOf('*') === -1) {

        this.options.title += ' <strong class="text-danger">*</strong>';

      }
      switch (this.layoutNode.type) {
</pre>

I also removed the similar line from the switch case for   // Containers - arrays and fieldsets

<pre>
        // Containers - arrays and fieldsets
        case 'array': case 'fieldset': case 'section': case 'conditional':
        case 'advancedfieldset': case 'authfieldset':
        case 'selectfieldset': case 'optionfieldset':
          this.options.messageLocation = 'top';
        break;
</pre>

I will try to fix for you and do a PR but I have never done that before :)

**Comment by dschnelldavis** [comment]
I merged your pull request, and it looks like this is working again.
