### ISSUE TITLE
Setting data programmatically

### ISSUE THREAD

**Issue by Thorski** [dschnelldavis/angular2-json-schema-form#106]
Is it possible to change the form data and have the form be updated?

For instance, a user clicks a button or checkbox on the form and I want my code to insert
a value in a field and have it show up on the form?   

I have tried setting detailForm.data (where I have passed [form]="detailForm" in component template).
It does not update on the screen.

Another use case I have is an array of things and I want a checkbox on each array item which is 'default' and only one can be checked, so I want on onChanges to unset the other checkbox.

Thanks.

**Comment by Thorski** [comment]
Does anybody know how to keep the form up to date with the bound data?

**Comment by tmburnell** [comment]
This might be related to this https://github.com/dschnelldavis/angular2-json-schema-form/issues/51.  If 2-way binding was properly being handled it should reflect all changes.

**Comment by dschnelldavis** [comment]
@Thorski @tmburnell Yes, This is closely related to #51 , so I'm closing this thread, and we'll track it there instead.

At the moment, you can update the input data and it will update the form. So in that sense you can set data programatically. However, doing so currently causes the entire form to be re-rendered and any selected control to be de-selected, which is really annoying for the user.

The correct way to do this instead would be to support full 2-way binding, which will take some effort to add, but is on the to-do list.
