### ISSUE TITLE
MaterialModule Deprecation 

### ISSUE THREAD

**Issue by janstadt** [dschnelldavis/angular2-json-schema-form#107]
Pulled down the latest code and built and am getting an error around MaterialModule not being found. 

It was deprecated in [2.0.0-beta.10](https://github.com/angular/material2/releases/tag/2.0.0-beta.10) and removed in [2.0.0-beta.11](https://github.com/angular/material2/releases/tag/2.0.0-beta.11) 

https://github.com/angular/material2/blob/master/CHANGELOG.md#breaking-changes 

Whats odd is you have a lock for beta.10 and that is what is being installed yet the module still doesnt exist.

**Comment by aconanlai** [comment]
I can confirm this behavior.

**Comment by Davepar** [comment]
Actually, the package isn't locked to beta10. It will currently load beta12. You can temporarily get around that by removing the caret "^" in front of the @angular/material line, but when I tried that I starting getting other dependency errors.

I just submitted a pull request that works with beta12.

**Comment by janstadt** [comment]
Yeah I see the carrot but thought the lock file showed 10. Oh well, glad to see your PR.

**Comment by dschnelldavis** [comment]
I merged the pull request and published a new version to NPM, 0.5.0-alpha.9, with full support for @angular/material 2.0.0-beta.12.
