### ISSUE TITLE
Cant build in prod

### ISSUE THREAD

**Issue by Alrok** [dschnelldavis/angular2-json-schema-form#109]
When i try to build project in prod, i catch error

`ERROR in Error: Template parse errors:
Can't bind to 'mdDatepickerToggle' since it isn't a known property of 'button'. (" !formControl?.dirty"
        align="end">{{options?.placeholder}}</md-hint>
      <button mdSuffix [ERROR ->][mdDatepickerToggle]="picker"></button>
    </md-input-container>
    <md-datepicker #picker
"): ng:///../node_modules/angular2-json-schema-form/angular2-json-schema-form.d.ts.ɵbl.html@25:23
`

**Comment by dschnelldavis** [comment]
This was a problem with the Material Design library. They changed all their prefixes from "md..." to "mat..." and recently stopped supporting the old syntax. So "mdDatepickerToggle" is now "matDatepickerToggle".

The latest version of angular2-json-schema-form (currently 0.5.0-alpha.14) has completely switched to the new prefixes and should no longer cause any errors like this.
