### ISSUE TITLE
Condition ignored on section sub-items

### ISSUE THREAD

**Issue by Davepar** [dschnelldavis/angular2-json-schema-form#111]
Using "condition" on a top level item works fine, but doesn't work inside "section" (and I assume "fieldset" and others). The condition isn't being processed at all.

Related: the conditional item in the ASF Kitchen Sink example doesn't appear to be set up correctly. Looking at the root.component.ts code, it should be using "model" instead of "modelData" in the condition. And it would be a more useful example if it depended on a different field rather than itself.

**Comment by Davepar** [comment]
This is fixed for my case now. Thanks. I guess the fix was in 3108eda.

**Comment by dschnelldavis** [comment]
Cool. If it happens again, please post an example, and I'll look into it.
