### ISSUE TITLE
MatAutocompleteModule is not an NgModule

### ISSUE THREAD

**Issue by qwe852147** [dschnelldavis/angular2-json-schema-form#114]
I have install latest version but this error  happen.
I can't find out where error
following is part of my package.json
` "dependencies": {
    "@agm/core": "1.0.0-beta.0",
    "@angular/animations": "^4.0.2",
    "@angular/cdk": "^2.0.0-beta.12",
    "@angular/common": "^4.0.2",
    "@angular/compiler": "^4.0.2",
    "@angular/core": "^4.0.2",
    "@angular/flex-layout": "^2.0.0-beta.9",
    "@angular/forms": "^4.0.2",
    "@angular/http": "^4.0.2",
    "@angular/material": "^2.0.0-beta.12",
    "@angular/platform-browser": "^4.0.2",
    "@angular/platform-browser-dynamic": "^4.0.2",
    "@angular/router": "^4.0.2",
    "@ngx-translate/core": "6.0.1",
    "@ngx-translate/http-loader": "0.0.3",
    "ag-grid": "9.0.3",
    "ag-grid-angular": "9.0.3",
    "angular-tree-component": "3.3.0",
    "angular2-datatable": "0.6.0",
    "angular2-json-schema-form": "^0.5.0-alpha.11",`

**Comment by ckannon** [comment]
same problem.

**Comment by dschnelldavis** [comment]
I'm not sure what caused this.

However, as of version 0.5.0-alpha.13, all unneeded Material Design modules (including MatAutocompleteModule) were removed, which should solve your problem.

As for dependancies, angular2-json-schema-form requires these:

```javascript
  "dependencies": {
    "@angular/cdk": "^2.0.0-beta.12",
    "@angular/common": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/flex-layout": "^2.0.0-beta.9",
    "@angular/forms": "^4.0.0",
    "@angular/material": "^2.0.0-beta.12",
    "@angular/platform-browser": "^4.0.0",
    "ajv": "^5.2.4",
    "angular2-json-schema-form": "^0.5.0-alpha.13",
    "lodash": "4.x",
    "rxjs": "5.x"
  },
```
