### ISSUE TITLE
0.5.0-alpha11 breaking changes?

### ISSUE THREAD

**Issue by fusionbeam** [dschnelldavis/angular2-json-schema-form#115]
Hi,

After upgrading from 0.5.0-alpha10 to 0.5.0-alpha11 the component is no longer working.
Are any configuration changes mandatory for this upgrade?

Here is a console log dump.

`
JsonSchemaFormComponent.html:9 ERROR TypeError: Cannot read property 'debug' of undefined
    at Object.eval [as updateDirectives] (JsonSchemaFormComponent.html:14)
    at Object.debugUpdateDirectives [as updateDirectives] (core.es5.js:13067)
    at checkAndUpdateView (core.es5.js:12251)
    at callViewAction (core.es5.js:12599)
    at execComponentViewsAction (core.es5.js:12531)
    at checkAndUpdateView (core.es5.js:12257)
    at callViewAction (core.es5.js:12599)
    at execComponentViewsAction (core.es5.js:12531)
    at checkAndUpdateView (core.es5.js:12257)
    at callViewAction (core.es5.js:12599)

`

**Comment by fusionbeam** [comment]
here is how I use it:
`
<json-schema-form
                            framework="bootstrap-3"
                            [schema]="jsonSchema.schemaObject.schema"
                            (onSubmit)="yourOnSubmitFn($event)">
                    </json-schema-form>
`
no configurations, just module imports as instructed in the README

**Comment by fusionbeam** [comment]
turned out the reason for failure was the schema content. settled for draft4 schemas, they seem to work best so far.

**Comment by dschnelldavis** [comment]
The new version has an updated [function to automatically convert any schema to draft 6](https://github.com/dschnelldavis/angular2-json-schema-form/blob/master/src/lib/src/shared/convert-schema-to-draft6.function.ts), which probably caused your problem.

In theory, this function should work with schemas in draft 1, 2, 3, 4, or 6 format, though in practice it's only been tested with drafts 3, 4, and 6.

So if you have a schema from a previous draft that isn't working, please post it here, so I can figure out where the error is and update the schema converter.

Thanks!
