### ISSUE TITLE
If the array property addable is false, only the first element of the array is showed

### ISSUE THREAD

**Issue by efrengp** [dschnelldavis/angular2-json-schema-form#119]
If we define in our json the property addable === false, not all the array elements are showed, only the first one.

There is a wrong placed condition in layout.function.ts (line 310)

**Comment by efrengp** [comment]
Moving the line 310 of layout.functions.ts to the line 340 (before 
let buttonText:string = 'Add'; 
the problem is solved.

All the array is showed and the Add button isn't displayed

**Comment by efrengp** [comment]
This bug has been fixed in the last update

**Comment by efrengp** [comment]
I'm sorry, the bug still exits

**Comment by dschnelldavis** [comment]
I'm having trouble recreating this. Can you post an example schema and layout?

**Comment by efrengp** [comment]
With the last update, you've solved it.

You've added this code to layout.functions.ts and now it works in all the cases. Thanks!

 // If needed, add button to add items to array
        if (newNode.options.addable !== false &&
          newNode.options.minItems < newNode.options.maxItems &&
          (newNode.items[newNode.items.length - 1] || {}).type !== '$ref'
        )

**Comment by dschnelldavis** [comment]
@efrengp Got it. Thanks for the update.
