### ISSUE TITLE
bootstrap 4 support

### ISSUE THREAD

**Issue by stalsma** [dschnelldavis/angular2-json-schema-form#125]
I coded up an implementation that uses bootstrap 4.  It was very straightforward, in that it only required me to setup the calls to the correct external library; everything else was identical to the bootstrap 3 code.

I saw in your notes that you were looking for bootstrap4 support; surely it has to be more complex that what I did.  Before submitting a pull-request, I'd like to know your thoughts on what else needs to be done.

**Comment by dschnelldavis** [comment]
I originally had in mind to use [ng-bootstrap](https://github.com/ng-bootstrap/ng-bootstrap), which has a whole bunch of custom controls, similar to Material Design.

However, I don't have time to implement that right now. So if you've got a working framework that just uses CSS, go ahead and submit a pull request and I'll be glad to add it.

Put the new component and module in their own folder, next to Bootstrap 3 and Material Design:
```
src/lib/src/framework-library/bootstrap-4-framework
```

It will also need to be referenced in these files:

[src/lib/index.ts](https://github.com/dschnelldavis/angular2-json-schema-form/blob/master/src/lib/index.ts)
[src/lib/src/framework-library/framework-library.module.ts](https://github.com/dschnelldavis/angular2-json-schema-form/blob/master/src/lib/src/framework-library/framework-library.module.ts)
[src/lib/src/framework-library/framework-library.service.ts](https://github.com/dschnelldavis/angular2-json-schema-form/blob/master/src/lib/src/framework-library/framework-library.service.ts)

Just duplicate the lines for Bootstrap 3 and change the number.

Your framework might eventually get replaced with one that uses  ng-bootstrap, but that could take quite a while, and it would be great to have something to use in the meantime.

Thanks!

**Comment by stalsma** [comment]
That's pretty much what I did.  I am also using ng-bootstrap for the rest of my project, but it shines on the component side of things (button-based dropdowns, etc.).  But not so much simple controls.  I guess one could add those in (widgets?) or replace the standard <select> with the ng-dropdown, but then parity across the framework options might get lost.  Not sure of that's a priority or not.

**Comment by dschnelldavis** [comment]
Sounds interesting. Please post a pull request. I'd like to try it out.

What do you mean by "parity across the framework options might get lost"?

If you're already using ng-bootstrap, that's great, because it means that even if your framework doesn't use all the ng-bootstrap widgets right now, as long as it's already compatible, it should be easy to add those widgets later.

**Comment by dschnelldavis** [comment]
Merged into main library as of version 0.6.0-alpha.2.
