### ISSUE TITLE
onChanges() called without value for datepicker field

### ISSUE THREAD

**Issue by yonghongren** [dschnelldavis/angular2-json-schema-form#127]
When a datepicker field changes, onChanges() is called twice, first with the correct value, and then again without value for such a field. In following simple example, 

  schema = {
    'type': 'object',
    'properties': {
      'name': { 'type': 'string' },
      'dob': { 'title': 'Date', 'type': 'string' }
    }
  };

  layout = [
    { 'key': 'name' },
    { 'key': 'dob', 'type': 'date' },
  ];

Picking a date for 'dob' gets onChanges  called twice with data as below:

{dob: "2017-10-25"}
{}

Tested with the latest version (0.5.0-alpha.14).

**Comment by dschnelldavis** [comment]
Good catch, thanks.

Fixed as of version 0.5.0-alpha.15.
