### ISSUE TITLE
Submit button label

### ISSUE THREAD

**Issue by subratawebops** [dschnelldavis/angular2-json-schema-form#129]
When I'm creating a form the button is labelled as "Submit", how do I change it to e.g. "Create"?

**Comment by dschnelldavis** [comment]
You set the button text in the layout.

Here's a very simple example you can try out in [the playground](https://angular2-json-schema-form.firebaseapp.com) to see how it works:
```javascript
{
  "schema": {
    "type": "object",
    "properties": {
      "first_name": { "type": "string" },
      "last_name": { "type": "string" }
    }
  },
  "layout": [ "*", { type: "submit", title: "Create" } ]
}
```
