### ISSUE TITLE
Unable to build latest Code getting below TypeError: args.indexOf is not a function error

### ISSUE THREAD

**Issue by naveenatti** [dschnelldavis/angular2-json-schema-form#131]
Unable to build latest Code in windows machine getting below TypeError: args.indexOf is not a function error please suggest answer
[error Image](https://s1.postimg.org/36v4g5ukxr/error.png)

**Comment by dschnelldavis** [comment]
Yes, I'm having trouble converting the library to support Angular 5.

I'm building on Mac OS, and getting the same error message. Any suggestions for how to resolve it would be appreciated.

For now, if you roll back to version 0.5.0-alpha.16 (the commit immediately before "Add Angular 5 support"), it should build correctly (though, obviously, it won't work with Angular 5).

**Comment by dschnelldavis** [comment]
This is fixed in version 0.6.0-alpha.1.
