### ISSUE TITLE
Single-App seed

### ISSUE THREAD

**Issue by AlexanderDexler** [dschnelldavis/angular2-json-schema-form#135]
[x] Support request

Hi I'm completely new, so i should have the latest versions installed. 

After fighting with integrating HammerJS, MaterialDesign, making some configuration issues (including library-folder from demo) etc I end up in

**ERROR TypeError: Cannot read property 'title' of undefined (angular2-json-schema-form.es5.js:26329)
MaterialDesignFrameworkComponent.prototype.setTitle = function () {
...
}**

So could you provide a running single seed project with an appearing html-form based on a json-schema? This would be very greatful! I'm not able to get it running. Thanks a lot!

Angular CLI: 1.5.0
Node: 8.9.1
OS: win32 x64
Angular: 5.0.1
angular/cdk: 5.0.0-rc0
angular/cli: 1.5.0
angular/flex-layout: 2.0.0-beta.10-4905443
angular/material: 5.0.0-rc0
angular-devkit/build-optimizer: 0.0.32
angular-devkit/core: 0.0.20
angular-devkit/schematics: 0.0.35
ngtools/json-schema: 1.1.0
ngtools/webpack: 1.8.0
schematics/angular: 0.1.2
ypescript: 2.4.2
webpack: 3.8.1

**Comment by dschnelldavis** [comment]
Excellent idea. Here you go:

[Seed App for Bootstrap 3](https://github.com/dschnelldavis/ng-jsf-bootstrap3-seed)

[Seed App for Material Design](https://github.com/dschnelldavis/ng-jsf-material-design-seed)

They're not fancy, but they should be enough to get you started. Let me know if you have trouble running either of them.
