### ISSUE TITLE
Material-design

### ISSUE THREAD

**Issue by gconesa** [dschnelldavis/angular2-json-schema-form#14]
I try to use material design in the form.

<json-schema-form *ngIf="myData"
  [form]="jsonFormObject"
  [framework]="material-design"
  loadExternalAssets="true"
  (onSubmit)="yourOnSubmitFn($event)">
</json-schema-form>

But it's not working, always used bootstrap-3.

**Comment by jh-code** [comment]
Did you also install `@angular/material` and also put the `MaterialModule.forRoot()` in the imports of your NgModule?

**Comment by gconesa** [comment]
Yes I put  MaterialModule.forRoot() in the imports of my NgModule.

imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    AppRoutingModule,
    DateValueAccessorModule,
    MaterialModule.forRoot(),
    Md2Module.forRoot(),
    FlexLayoutModule.forRoot(),
    JsonSchemaFormModule.forRoot()
  ],

**Comment by marc101101** [comment]
is there any solution? got the same issue :(

**Comment by zhejingl** [comment]
I am having the same issue, does anyone have solution?
Thanks

**Comment by zhejingl** [comment]
I figured out. 
In the template file that refer to the framework type, give the name of the framework you defined in the .ts file, then in the .ts file, put the 'material-design' as the value of the name. So here is the .html:
<json-schema-form
  [form]="questionSchema"
  [framework]="frameworktype"
  [loadExternalAssets]="true"
  (onSubmit)="submitquestions($event)">
</json-schema-form>


then in the class (.ts).
frameworktype='material-design'

It works for me..

**Comment by FelschR** [comment]
The issue is/was that `[framework]="material-design"` expects `material-design` to be a variable.
When you just want to pass a value directly to an argument in Angular leave the brackets like so:
`framework="material-design"`

Then there is also no need to declare that variable like @zhejingl proposed.

**Comment by dschnelldavis** [comment]
Material Design is now the default framework, so you don't have to set anything to use it.

To use the Bootstrap 3 framework instead, use either
`framework="bootstrap-3"`
or
`[framework]="'bootstrap-3'"` (note the nested quotes: " ' ... ' " )

I've also updated the readme to clarify this.

**Comment by catull** [comment]
@dschnelldavis 
Unfortunately, if I want to use Bootstrap 3, I still have to import '@angular/material', although I am not using it.

See issue #199.

Can you please clean up the dependencies ?
