### ISSUE TITLE
About oneOf or conditional visibility

### ISSUE THREAD

**Issue by fbatibay** [dschnelldavis/angular2-json-schema-form#15]
Do you have any plans about making conditional schemas or how can i (or we) start to make this functionality with your library?

**Comment by dschnelldavis** [comment]
I think we already have basic support for oneOf. I also expect support for oneOf / anyOf / allOf to improve in the future, though it may take a while.

This is an old issue, so I'm going to close it, but know improved support is on the long term to-do list.

Also, if you have an example schema, please post it, and I'll add it to the demonstration playground, so we can get a better idea of exactly what we need to make it work.
