### ISSUE TITLE
Validate on init

### ISSUE THREAD

**Issue by gconesa** [dschnelldavis/angular2-json-schema-form#16]
Is there a way to validate the form at the beginning?

**Comment by dschnelldavis** [comment]
Yes, just set ```validateOnRender = true``` in the options.

The best practice is to set the options in your component:
```javascript
yourFormOptions: any = {
  validateOnRender: true
}
```

Then pass them to the form in your template:
```html
<json-schema-form
  [options]="yourFormOptions"
  [schema]="yourJsonSchema">
</json-schema-form>
```

Though if you want, you can skip a step and just do it all in the template:
```html
<json-schema-form
  [options]="{ validateOnRender: true }"
  [schema]="yourJsonSchema">
</json-schema-form>
```

For more information about other settings, look at the source of ```src/library/json-schema-form.service.ts``` . The object ```globalOptionDefaults``` contains the default form settings, and comments about what most of the settings do.
