### ISSUE TITLE
Add button in array

### ISSUE THREAD

**Issue by gconesa** [dschnelldavis/angular2-json-schema-form#17]
I tried to change the add button in array type. I used:

form": [
    {
      "key": "products",
      "add": "New product",
      "items": [
        "products[].product",
        "products[].quantity",
        "products[].unity",
        {
          "key": "products[].description",
          "type": "textarea"
        }
      ]
    },
    {
      "type": "submit",
      "style": "btn-info",
      "title": "Save"
    }
  ]

But the text in the button don't change

**Comment by dschnelldavis** [comment]
Fixed in 0.5.0-alpha.3.
