### ISSUE TITLE
can't bind to 'form' since it isn't a known property of 'json-schema-form'

### ISSUE THREAD

**Issue by rajesh-tammina** [dschnelldavis/angular2-json-schema-form#18]
can you please help me why i am getting this issue.

**Comment by benyaminshoham** [comment]
Please attach your code sample and describe what are you doing when getting this error.

**Comment by rajesh-tammina** [comment]
Error got solved for me. Actually I have imported JsonSchemaFormModule in the appModule only. I didn't import in my sub module. Now i have tried importing that in my submodule also. It's working perfectly.
Thank you.

**Comment by benyaminshoham** [comment]
If resolved, please mark issue as "closed"
