### ISSUE TITLE
Problem with float number

### ISSUE THREAD

**Issue by gconesa** [dschnelldavis/angular2-json-schema-form#19]
There is an error when I tried to write a float number(example: 3,2 or 3.2), the data field was deleted.
I put property type as number.

**Comment by benyaminshoham** [comment]
What error did you get?
What do you mean " the data field was deleted." ?
Please describe what are you doing when getting this issue, and attach a code sample.

**Comment by gconesa** [comment]
I use this in the json schema :
"properties": {
      "number": {
        "title": "Number",
        "type": "number"
      }
}

When I try tu put ',' or '.' in the input field created didn't show the ',' or '.'

**Comment by dschnelldavis** [comment]
Commas aren't allowed in number fields.

A single decimal is allowed, and the library initially used extra input validation to prevent additional decimals from being entered, so your problem may have been a side effect of that validation not working correctly.

Looking at it again, I think browsers do a good job handling number input on their own, so as of 0.5.0-alpha.4 I've removed all the additional input validation, which should permanently fix tis issue.
