### ISSUE TITLE
How I can add button to form?

### ISSUE THREAD

**Issue by person2713** [dschnelldavis/angular2-json-schema-form#208]
Can you tell me how add additional button to form, that generate by json-schema?

**Comment by lucasgranberg** [comment]
Add it to your layout just like a submit button.
```js
layout = [
    ... ,
    { 
        type: 'button', 
        title: 'My Action', 
        onClick: function(event){
            console.log("clicked",event);
        }
   }
]
```

Then you have to add the layout to the directive as said in:
https://github.com/dschnelldavis/angular2-json-schema-form#advanced-use

**Comment by person2713** [comment]
Thank you, can you say how put this button inline to submit button, that was generate by angular? I have use layout?

**Comment by lucasgranberg** [comment]
Check out the examples. There is an example for putting two inputs side by side.
https://angular2-json-schema-form.firebaseapp.com/

Something like:
```ts
  layout = [
    {
      type: 'flex',
      'flex-flow': 'row wrap',
      items: [
        {
          type: 'button',
          title: 'My Action 1',
          onClick: function (event) {
            console.log('clicked 1', event);
          }
        },
        {
          type: 'button',
          title: 'My Action 2',
          onClick: function (event) {
            console.log('clicked 2', event);
          }
        }
      ]
    }
  ];
```

**Comment by person2713** [comment]
Thanks.

**Comment by person2713** [comment]
I saw this example, but don't found.

**Comment by person2713** [comment]
do you have example where additional button bind to function on typescripts?
