### ISSUE TITLE
creating custom widget

### ISSUE THREAD

**Issue by padmajamanish** [dschnelldavis/angular2-json-schema-form#21]
Can you post any examples related to Add new 'custom-control' widget in angular2-json-schema

**Comment by chivalme** [comment]
Here is a example of custom widget:

https://github.com/dschnelldavis/angular2-json-schema-form/blob/master/src/lib/src/framework-library/material-design-framework/material-datepicker.component.ts

**Comment by dschnelldavis** [comment]
Thanks @chivalme !

There are also many examples of different widgets [here](https://github.com/dschnelldavis/angular2-json-schema-form/tree/master/src/lib/src/widget-library) and [here](https://github.com/dschnelldavis/angular2-json-schema-form/tree/master/src/lib/src/framework-library/material-design-framework).

**Comment by neil-coutinho** [comment]
@dschnelldavis is there any documentation related with creating custom widgets?
Thank you
