### ISSUE TITLE
How get value from input field?

### ISSUE THREAD

**Issue by person2713** [dschnelldavis/angular2-json-schema-form#229]
How get value from input field? I try add additional information when users type in input field. How can I get access to value in this input?

**Comment by Alex130** [comment]
Hi, can you provide more information on what you are trying to do?

**Comment by person2713** [comment]
Ok. I have an input filed (attributeId of the object). I want make next thing. When user type attributeId I want that in some field appear name of this attributeId. I think make this use asynchronous request, but I don't know hot get value of Id, because the all html generated by angular-json-form liblrary. 
May be there is way mark input field in json schema and then use it?

**Comment by person2713** [comment]
May be there is way mark input field in json schema and then use it?

**Comment by Alex130** [comment]
Hi,
you can  probably use onChanges() to get the form values while the user is typing, or if you want to wait, add a button in your layout with a click() action and pass the "model" object.
You can put your data in another input using a [()] binding with ngModel.

**Comment by person2713** [comment]
I want next: when user inputId of object - appear field with name of object below input tag and it work automatically.  Also when user erase field with name disappear.

**Comment by Alex130** [comment]
You can use a simple condition for this, you can find the details in
another recent bug report

**Comment by person2713** [comment]
But, I want send async request and if object exists output it's name.

**Comment by person2713** [comment]
I think you speak about this example:
`{ "title": "Yes I want spam.",
          "type": "checkbox",
          "key": "comments[].spam",
          "condition": "model.comments[arrayIndex].email"
        }`
