### ISSUE TITLE
How set default value for layout?

### ISSUE THREAD

**Issue by person2713** [dschnelldavis/angular2-json-schema-form#234]
How set default value for layout? Try this, but it does't work.
```
`{ key: 'ky',
        title: 'Ky',
      type: 'text',
        default: '1111'},`
```
Get next:
![image](https://user-images.githubusercontent.com/23407273/37451904-1d3ad7f2-2844-11e8-902c-a4aa8376c988.png)

I will appreciate for any help.

**Comment by catull** [comment]
The default value is a data characteristics, not a layout one.

**Comment by catull** [comment]
I meant, a _schema_ characteristic ....

**Comment by person2713** [comment]
Ok, I can configure input field that I add by layout? For example set initial value for input field and so on.

**Comment by catull** [comment]
@person2713 I am sorry, but you have to learn a bit on your own, too.

I get the feeling that you are afraid of experimenting and finding examples.
Start by searching for "tutorial JSON schema form", and take it from there.

You will find a lot of material.

**Comment by person2713** [comment]
I knew why I get undefined, because when browser render page I got next error:
`/Objects/1/object/attributes/undefined/value`
that means statement "Objects[].object.attributes[].value" wrong.
