### ISSUE TITLE
Function don't work if I write layout (form definition) in json file

### ISSUE THREAD

**Issue by person2713** [dschnelldavis/angular2-json-schema-form#236]
Should function work if I set layout in json file? 
Below json file with form definition:
```
`{
 "layout": [
      "*",
      {
        "type": "section",
        "htmlClass": "row",
        "items": [
          {
            "type": "section",
            "htmlClass": "col-md-1",
            "items": [
              {
                "type": "submit",
                "title": "Apply"
              }
            ]
          },
          {
            "type": "section",
            "htmlClass": "col-md-1",
            "items": [
              {
                "type": "button",
                "title": "Save",
		"onClick": "() => { this.schemaFormComponent.formData.name = this.jsonName.substr(0, this.jsonName.indexOf('.')); this.updateConfiguration(this.schemaFormComponent.formData);}"
              }
            ]
          }
        ]
      }
     ]
}`
```
I try it does't work. May be I did some mistake. 
I will appreciate for any help.

**Comment by catull** [comment]
Have you tried:

```json
"onClick": "() => { model.name = this.jsonName.substr(0, this.jsonName.indexOf('.')); this.updateConfiguration();
}"
```

And have the method `updateConfiguration()` work on the form data directly, rather than passing it in from the JSON form.

I habe no idea what `jsonName` is, you do not explain it.
We have to guess a lot here.

**Comment by person2713** [comment]
Ok, I give more explanation:
Above layout - its layout for parent component. On parent component there are menu with json files. When we click on save button triggers this.updateConfiguration() method, that take changed information from child component and send it to backend. 
```
`public updateConfiguration(settings) {
        Log.create('EndpointSettingsTabComponent.saveConfiguration(settings)').d(settings);
        this.endpointSettingsService.updateConfiguration(settings).subscribe();
    }`
```

**Comment by person2713** [comment]
Can you show how use two way binding in angular2 json schema. I search and find next:
[(data)]=""

**Comment by catull** [comment]
React by design has single binding, one-way.
Don't know how of if it supports 2-way binding.

In Angular (2, 4, 5, 6, ....), you specify 1-way binding with 
```
[data]=''
```
and 2-way binding with
```
[(data)]=''
```

Not sure this helps you in any way with your React project.

**Comment by person2713** [comment]
Catull, thank you for your advices. Summary I find an issue of all my problem. In projects use very old version of angular2-json-schema-form.

**Comment by person2713** [comment]
Catull, can you give me example how to set framework for css style?
I read docs, saw demo and try next example:
```
`<json-schema-form
  loadExternalAssets="true"
  [framework]="'bootstrap-3'"
  [schema]="schema"
  [data]="data"
  [layout] = "layout"
  [options]="options"
  (onChanges)="changeForm($event)"
  (onSubmit)="submitForm($event)"
  (isValid)="validateForm($event)"
  (validationErrors)="errorsForm($event)">
</json-schema-form>`
```
And try this way:
```
`[loadExternalAssets]="true"
  [framework]="'bootstrap-3'"`
```
But it doesn't work. May I do something wrong?

**Comment by catull** [comment]
What does your app.module.ts look like, again ?

My guess is you do not have it that way:

```typescript
// all your imports

import {
  Bootstrap3FrameworkModule,
  FrameworkLibraryService,
  JsonSchemaFormModule,
  JsonSchemaFormService,
  WidgetLibraryService
} from 'angular2-json-schema-form';

@NgModule({
  declarations: [
    // all you own components
    AppComponent
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    FormsModule,
    HttpClientModule,
    RouterModule.forRoot(routes),
    Bootstrap3FrameworkModule,
    JsonSchemaFormModule.forRoot(Bootstrap3FrameworkModule)
  ],
  providers: [
    JsonSchemaFormService,
    FrameworkLibraryService,
    WidgetLibraryService
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
???

Next time, provide some more error diagnostics, it is very hard to guess and it wastes our time.

The example above is obviously for Angular.

**Comment by person2713** [comment]
Yes, I did the same as were in demo and that you wrote above. But I still get next error:
![image](https://user-images.githubusercontent.com/23407273/37696647-4988abf0-2ce9-11e8-9e83-adf5056411eb.png)

**Comment by person2713** [comment]
Catull thanks much for you help. I resolved problem.

**Comment by person2713** [comment]
Catull, do you know liblary angular2-json schema support condition or not?

**Comment by catull** [comment]
Not sure it does, I have not used it yet.

**Comment by person2713** [comment]
I check this. It works well.

**Comment by rmayuri** [comment]
@person2713 and @catull 
I am using bootstrap4module framework, the form is getting loaded but I am not able to read the form values,
could you please any example to read the values and applying css.
below are my fiels for your reference,

login.component.ts
---------------------
import { Component } from '@angular/core';
@Component({
	   selector: 'app-login',
	   templateUrl: './login.component.html',
	   styleUrls: ['./login.component.css']
	 })

export class LoginComponent {
  title = 'Optum Navigator';
  mySchema = {
    "properties": {
      "msid": {
        "type": "string",
        "required":true,
        "htmlClass": "mystyle",
      },
      "password": {
        "type": "string",
        "widget": "password",
        "required":true
       },      
      }
};
myform = {
     "form": [
     "msid",
     "password",
         {
       "type": "submit",
       "name": "btnSubmit",
       "title": "Login",
       
     }
   ]
   };
  public OnSubmitFn(event:any){
    console.log("login"+event);
  }
}

login.component.html
--------------------------
<div class="div1"><h1>{{title}}</h1><br/><br/>
        <div class="div2">
              <json-schema-form
            loadExternalAssets="true"
            [schema]="mySchema"
           
            [form]="myform"
            [layout]="mylayout"
            (onSubmit)="OnSubmitFn($event)"
            >       
            </json-schema-form> 
            
        </div>
    </div>


Thanks in advance.

**Comment by person2713** [comment]
rmayuri, can you send console output from google chrome?

**Comment by person2713** [comment]
And where declaration of the mylayout?

**Comment by person2713** [comment]
above there are examples how you have to write html code. For your example it will be like this:
```
<json-schema-form
  loadExternalAssets="true"
  [framework]="'bootstrap-4'"
  [schema]="mySchema"
  [data]="myform"
  [layout] = "mylayout"
  (onSubmit)="submitForm($event)">
</json-schema-form>
```
But I didn't see declaration of the "mylayout". First verify your schema, data and layout in playground.

**Comment by rmayuri** [comment]
@person2713 and @catull 

the console output is null,

below are the files,

**login.component.ts**
---------------------

import { Component } from '@angular/core';
@Component({
	   selector: 'app-login',
	   templateUrl: './login.component.html',
	   styleUrls: ['./login.component.css']
	 })

export class LoginComponent {
  title = 'Optum Navigator';
  mySchema = {
    "properties": {
      "msid": {
        "type": "string",
        "required":true,
        
      },
      "password": {
        "type": "string",
        "widget": "password",
        "required":true
       },       
        "submit":{
        "type": 'submit',
        "title": 'Login',
       }
     }
};
mylayout = [
  "*",
{
    key: 'submit',
    type: 'submit',
   title: 'Login',
    htmlClass: 'mystyle',
    fieldHtmlClass: 'mystyle', 
     labelHtmlClass: 'mystyle', 
     itemLabelHtmlClass: 'mystyle',
     activeClass: 'mystyle',
     labelHelpBlockClass: 'mystyle'
  }
];  
  public OnSubmitFn(event:any){
    console.log("login"+event);
  }
}


**login.component.css**
-----------------------
h1{margin-bottom: 0;
    font-size: 50px;
    font-family: sans-serif;
	color: orange;
	text-align:center;
}

.div1 {
    position:fixed !important;
    position: absolute;
    margin-left:150px;
    background-color: #f3f2f2;
        width: 1000px;
        height: 450px;
          }
    
    .div2 {
        position :absolute;
    background-color: white;
    margin-left:300px;
    margin-bottom:500px;
        width: 400px;
        height: 300px;          
    }
    .mystyle {
        background-color: #4CAF50; /* Green */
        border: none;
        color: white;
        padding: 15px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 100px;
    }
    
**login.component.html**
------------------------

        <div class="div2">
              <json-schema-form
            loadExternalAssets="true"
            [schema]="mySchema"
            [layout]="mylayout"          
            (onSubmit)="OnSubmitFn($event)"
            >       
            </json-schema-form> 
             </div>
  

on clicking on login button its giving console output as "loginnull" , and the css I given for login button also not getting applied.


Please provide any inputs to read form data and applying css for specific element.
thanks in advance
