### ISSUE TITLE
Error when use "@angular/material": "2.0.0-beta.2"

### ISSUE THREAD

**Issue by gconesa** [dschnelldavis/angular2-json-schema-form#24]
When I used with "@angular/material": "2.0.0-beta.2" I had the next problem

"Unhandled Promise rejection: Template parse errors:
Can't bind to 'required' since it isn't a known property of 'md-input'.
1. If 'md-input' is an Angular component and it has 'required' input, then verify that it is part of this module.
2. If 'md-input' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
        [attr.minlength]="options?.minLength"
        [attr.pattern]="options?.pattern"
        [ERROR ->][required]="options?.required"
        [class]="options?.fieldHtmlClass"
        [disabled]="controlD"): MaterialInputComponent@8:8
Can't bind to 'disabled' since it isn't a known property of 'md-input'.
1. If 'md-input' is an Angular component and it has 'disabled' input, then verify that it is part of this module.
2. If 'md-input' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
        [required]="options?.required"
        [class]="options?.fieldHtmlClass"
        [ERROR ->][disabled]="controlDisabled"
        [id]="'control' + layoutNode?._id"
        [name]="controlName"
"): MaterialInputComponent@10:8
Can't bind to 'name' since it isn't a known property of 'md-input'.
1. If 'md-input' is an Angular component and it has 'name' input, then verify that it is part of this module.
2. If 'md-input' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
        [disabled]="controlDisabled"
        [id]="'control' + layoutNode?._id"
        [ERROR ->][name]="controlName"
        [placeholder]="options?.title"
        [readonly]="options?.readonly ? '"): MaterialInputComponent@12:8
Can't bind to 'placeholder' since it isn't a known property of 'md-input'.
1. If 'md-input' is an Angular component and it has 'placeholder' input, then verify that it is part of this module.
2. If 'md-input' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
        [id]="'control' + layoutNode?._id"
        [name]="controlName"
        [ERROR ->][placeholder]="options?.title"
        [readonly]="options?.readonly ? 'readonly' : null"
        [st"): MaterialInputComponent@13:8
Can't bind to 'readOnly' since it isn't a known property of 'md-input'.
1. If 'md-input' is an Angular component and it has 'readOnly' input, then verify that it is part of this module.
2. If 'md-input' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
        [name]="controlName"
        [placeholder]="options?.title"
        [ERROR ->][readonly]="options?.readonly ? 'readonly' : null"
        [style.width]="'100%'"
        [type]="lay"): MaterialInputComponent@14:8
Can't bind to 'type' since it isn't a known property of 'md-input'.
1. If 'md-input' is an Angular component and it has 'type' input, then verify that it is part of this module.
2. If 'md-input' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
        [readonly]="options?.readonly ? 'readonly' : null"
        [style.width]="'100%'"
        [ERROR ->][type]="layoutNode?.type"
        [value]="controlValue"
        (input)="updateValue($event)">
"): MaterialInputComponent@16:8
Can't bind to 'value' since it isn't a known property of 'md-input'.
1. If 'md-input' is an Angular component and it has 'value' input, then verify that it is part of this module.
2. If 'md-input' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
        [style.width]="'100%'"
        [type]="layoutNode?.type"
        [ERROR ->][value]="controlValue"
        (input)="updateValue($event)">
        <span *ngIf="options?.fieldAddo"): MaterialInputComponent@17:8
'md-input' is not a known element:
1. If 'md-input' is an Angular component, then verify that it is part of this module.
2. If 'md-input' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("
    <section [class]="options?.htmlClass">
      [ERROR ->]<md-input #inputControl
        [attr.aria-describedby]="'control' + layoutNode?._id + 'Status'"
    "): MaterialInputComponent@2:6 ; Zone: <root> ; Task: Promise.then ; Value: SyntaxError {__zone_symbol__error: Error: Template parse errors:
Can't bind to 'required' since it isn't a known property of 'md-input'…, _nativeError: ZoneAwareError, __zone_symbol__stack: "Error: Template parse errors:↵Can't bind to 'requi…http://localhost:4201/vendor.bundle.js:258970:35)", __zone_symbol__message: "Template parse errors:↵Can't bind to 'required' si…id + 'Status'"↵    "): MaterialInputComponent@2:6"} Error: Template parse errors:
Can't bind to 'required' since it isn't a known property of 'md-input'.
1. If 'md-input' is an Angular component and it has 'required' input, then verify that it is part of this module.
2. If 'md-input' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
        [attr.minlength]="options?.minLength"
        [attr.pattern]="options?.pattern"
        [ERROR ->][required]="options?.required"
        [class]="options?.fieldHtmlClass"
        [disabled]="controlD"): MaterialInputComponent@8:8
Can't bind to 'disabled' since it isn't a known property of 'md-input'.
1. If 'md-input' is an Angular component and it has 'disabled' input, then verify that it is part of this module.
2. If 'md-input' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
        [required]="options?.required"
        [class]="options?.fieldHtmlClass"
        [ERROR ->][disabled]="controlDisabled"
        [id]="'control' + layoutNode?._id"
        [name]="controlName"
"): MaterialInputComponent@10:8
Can't bind to 'name' since it isn't a known property of 'md-input'.
1. If 'md-input' is an Angular component and it has 'name' input, then verify that it is part of this module.
2. If 'md-input' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
        [disabled]="controlDisabled"
        [id]="'control' + layoutNode?._id"
        [ERROR ->][name]="controlName"
        [placeholder]="options?.title"
        [readonly]="options?.readonly ? '"): MaterialInputComponent@12:8
Can't bind to 'placeholder' since it isn't a known property of 'md-input'.
1. If 'md-input' is an Angular component and it has 'placeholder' input, then verify that it is part of this module.
2. If 'md-input' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
        [id]="'control' + layoutNode?._id"
        [name]="controlName"
        [ERROR ->][placeholder]="options?.title"
        [readonly]="options?.readonly ? 'readonly' : null"
        [st"): MaterialInputComponent@13:8
Can't bind to 'readOnly' since it isn't a known property of 'md-input'.
1. If 'md-input' is an Angular component and it has 'readOnly' input, then verify that it is part of this module.
2. If 'md-input' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
        [name]="controlName"
        [placeholder]="options?.title"
        [ERROR ->][readonly]="options?.readonly ? 'readonly' : null"
        [style.width]="'100%'"
        [type]="lay"): MaterialInputComponent@14:8
Can't bind to 'type' since it isn't a known property of 'md-input'.
1. If 'md-input' is an Angular component and it has 'type' input, then verify that it is part of this module.
2. If 'md-input' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
        [readonly]="options?.readonly ? 'readonly' : null"
        [style.width]="'100%'"
        [ERROR ->][type]="layoutNode?.type"
        [value]="controlValue"
        (input)="updateValue($event)">
"): MaterialInputComponent@16:8
Can't bind to 'value' since it isn't a known property of 'md-input'.
1. If 'md-input' is an Angular component and it has 'value' input, then verify that it is part of this module.
2. If 'md-input' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
        [style.width]="'100%'"
        [type]="layoutNode?.type"
        [ERROR ->][value]="controlValue"
        (input)="updateValue($event)">
        <span *ngIf="options?.fieldAddo"): MaterialInputComponent@17:8
'md-input' is not a known element:
1. If 'md-input' is an Angular component, then verify that it is part of this module.
2. If 'md-input' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("
    <section [class]="options?.htmlClass">
      [ERROR ->]<md-input #inputControl
        [attr.aria-describedby]="'control' + layoutNode?._id + 'Status'"
    "): MaterialInputComponent@2:6
    at SyntaxError.ZoneAwareError (http://localhost:4201/vendor.bundle.js:259399:33)
    at SyntaxError.BaseError [as constructor] (http://localhost:4201/vendor.bundle.js:141825:16)
    at new SyntaxError (http://localhost:4201/vendor.bundle.js:12032:16)
    at TemplateParser.parse (http://localhost:4201/vendor.bundle.js:46052:19)
    at JitCompiler._compileTemplate (http://localhost:4201/vendor.bundle.js:90943:68)
    at http://localhost:4201/vendor.bundle.js:90826:62
    at Set.forEach (native)
    at JitCompiler._compileComponents (http://localhost:4201/vendor.bundle.js:90826:19)
    at createResult (http://localhost:4201/vendor.bundle.js:90708:19)
    at ZoneDelegate.invoke (http://localhost:4201/vendor.bundle.js:258771:26)
    at Zone.run (http://localhost:4201/vendor.bundle.js:258567:43)
    at http://localhost:4201/vendor.bundle.js:259120:57
    at ZoneDelegate.invokeTask (http://localhost:4201/vendor.bundle.js:258804:31)
    at Zone.runTask (http://localhost:4201/vendor.bundle.js:258607:47)
    at drainMicroTaskQueue (http://localhost:4201/vendor.bundle.js:258970:35)
consoleError @ zone.js:516
_loop_1 @ zone.js:545
drainMicroTaskQueue @ zone.js:549
zone.js:518 "

**Comment by st0rm1x** [comment]
Had the same issues with you. Had to rollback to 2.0.0-beta.1 in order to compile and run it without errors

**Comment by rjsteinert** [comment]
Yup, same issue. It's the first thing I hit when setting this up for the first time.

**Comment by dschnelldavis** [comment]
Yep, the newer Angular Material releases completely broke the old version, to the point where I had to temporarily disable the entire Material framework in this library for a while.

However the new version of this library (v0.4.0-alpha7) has restored Angular Material and uses the latest version (Angular Material v2.0.0-beta.6), and includes preliminary support for some of the new widgets, like the slider and the date control. So it should work again (at least until beta.7 comes along).

I'll be working on this library more regularly now, so it should keep up with future upgrades to the Angular Material library more promptly in the future, and once Angular Material gets a final release, the breaking changes should stop completely.
