### ISSUE TITLE
Nested array errors

### ISSUE THREAD

**Issue by A-Barnes** [dschnelldavis/angular2-json-schema-form#25]
I am trying to generate a structure similar to the following:
```
[
    {
       "field":"..",
       "array_field": [
          {
               "another_field": "..",
               "array_field": [
                   {},{}, ...
               ]
          }
       ]
    },
    {}
]

```

Basically I am trying to create a nested structure of arrays and objects. I have attached my schema. The library loads the components correctly, but inputting data into the deeply nested fields throw a bunch of errors. Here is the error message:

![formissue](https://cloud.githubusercontent.com/assets/5101609/23326637/6b146122-fb4b-11e6-8717-5b17d7c3c90a.jpg)

Here is the schema:

```

{
  "schema": {
    "properties": {
      "tiers": {
        "type":"array",
        "items":{
           "$ref": "#/definitions/tiers_obj",
           "extendRefs":true
        }
      }
    },
    "definitions": {
      "tiers_obj":{
        "type":"object",
        "properties":{
            "min_amount":{
                "type":"integer",
                "title":"min amount"
            },
            "max_amount":{
                "type":"integer",
                "title":"max amount"
            },
            "Fees":{
                "title":"fees",
                "type":"array",
                "items":{
                    "$ref":"#/definitions/fees_obj"
                }
            }
        }
      },
      "fees_obj":{
        "type":"object",
        "title":"Fees_obj",
        "properties":{
            "ongoing_fee":{
                "type":"integer",
                "title":"ong"
            },
            "application_fee":{
                "type":"integer",
                "title":"app"
            }
        }
      }
    }
  }
}

```

**Comment by Alrok** [comment]
I have the same problem.
did you found solution?

**Comment by dschnelldavis** [comment]
Hmmm. One of the other updates must have broken the array functions. Sorry about that.

Arrays, including nested arrays, should all be working correctly again now. I tried your schema [here](https://angular2-json-schema-form.firebaseapp.com/), and it appears to be working fine in current version (0.5.0-alpha.6).
