### ISSUE TITLE
Can I control the order of output of the fields of the schema?

### ISSUE THREAD

**Issue by person2713** [dschnelldavis/angular2-json-schema-form#266]
Can I control the order of output of the schema fields without knowing the whole scheme? I mean something, like that:
```
{
  "schema": {
    "type": "object",
    "title": "Comment",
    "properties": {
      "name": {
        "title": "Name",
        "type": "string"
      },
      "email": {
        "title": "Email",
        "type": "string",
        "pattern": "^\\S+@\\S+$",
        "description": "Email will be used for evil."
      },
      "comment": {
        "title": "Comment",
        "type": "string",
        "maxLength": 20,
        "validationMessage": "Don't be greedy!",

      }
    }
  },
  "form": [
      {"key": "comment"},
      '*'
  ]
}

```
But without duplicate fields.

**Comment by catull** [comment]
@person2713

No, you cannot control the sequence of the fields without knowing them.

In fact, your "form" definition above is likely interpreted as:

```json
{
// ......
    "form": [
     { "key": "comment" },
     { "key": "name" },
     { "key": "email" },
     { "key": "comment" }
  ]
```

Thus, you get the duplication.

If you want a specific order of properties, your "schema" must reflect this order.
Once you have that, you can use a simple

```json
{
  "form": [
     '*'
   ]
}
```

or even leave out the "form" entirely.

Remember, this "short-cut" creates one field per row, which is great for mobile phones, but not for web browsers.

**Comment by person2713** [comment]
Thanks.
