### ISSUE TITLE
Render schema form horizontally

### ISSUE THREAD

**Issue by st0rm1x** [dschnelldavis/angular2-json-schema-form#29]
Hi, is there anyway I could render a HTML form horizontally like 
                     [LABEL] ==== [INPUT]
In an inline format?

I have tried putting on bootstrap classes but nothing seems to work. Any idea?

**Comment by dschnelldavis** [comment]
That's odd - Bootstrap classes should work. I'll look into it and get back to you with a better answer.

**Comment by agborkowski** [comment]
i think we will need somethink like "layout" parameter for parent container like in extjs:

https://docs.sencha.com/extjs/6.5.0/guides/components/forms.html

````
'Ext.form.Panel', {
    renderTo: document.body,
    title: 'User Form',
    height: 120,
    width: 585,
    defaults: {
        xtype: 'textfield',
        labelAlign: 'top',
        padding: 10
    },
    layout: 'hbox',
    items: [
        {
            fieldLabel: 'First Name',
            name: 'firstName'
        },
````

panels/sections can be mixed with hbox vbox ....

**Comment by dschnelldavis** [comment]
The new flexbox layout options should solve this for you.

Check out an example [here](https://angular2-json-schema-form.firebaseapp.com/).
