### ISSUE TITLE
Angular 4 RC version Support

### ISSUE THREAD

**Issue by alimohammad** [dschnelldavis/angular2-json-schema-form#30]
@dschnelldavis I am trying to implement this library on angular 4, its working fine. But due to its dependencies on angular 2 and material 2, I am having issues while creating a shrink wrap. 

What do you suggest.

**Comment by dschnelldavis** [comment]
The latest version (v0.4.0-alpha7) completely overhauls the the distribution packaging, following the example of the Angular-endorsed [angular-quickstart-lib](https://github.com/filipesilva/angular-quickstart-lib), which conforms to the official Angular Package Format. So it should now be 100% Angular 4 compatible.

I believe you should also be able to  create a shrink wrap with it, though I have not tested that. Could you tell me if the new version works for you?
