### ISSUE TITLE
Doesnt build in production mode at angular2-webpack.

### ISSUE THREAD

**Issue by Freest10** [dschnelldavis/angular2-json-schema-form#31]
Error message:
"Error encountered resolving symbol values statically. Calling function 'JsonSchemaFormModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in C:/Users/mmv/angular2-webpack-starter-master/src/app/app.module.ts, resolving symbol AppModule in C:/Users/mmv/angular2-webpack-starter-master/src/app/app.module.ts"

I had tried include like, as in the documentation:

@NgModule({
  declarations: [ AppComponent ],
  imports: [
    BrowserModule, FormsModule, HttpModule,
    MaterialModule.forRoot(), JsonSchemaFormModule.forRoot()
  ],
  providers: [],
  bootstrap: [ AppComponent ]
})

**Comment by dschnelldavis** [comment]
I believe this has been fixed in the latest version (v0.4.0-alpha7). That version has been tested and confirmed working with the latest Angular CLI, which uses Webpack.

Can you confirm wether or not it works with the setup you're using?
