### ISSUE TITLE
How to customized new widget?

### ISSUE THREAD

**Issue by qwe852147** [dschnelldavis/angular2-json-schema-form#32]
How to customized new widget? Example:file upload?
If I customized  a new widget,schema and form which one I show put customized type in?

**Comment by qwe852147** [comment]
I got it .
1.
Customized a new widget should add a new component which is your widget .

2.
Then in your component which have your "schema" or " form"  import "WidgetLibraryService" from 'angular2-json-schema-form'  and import your new widget component.

3.
Declare new variable which similar following
```
constructor( widgetLibrary: WidgetLibraryService) {
     widgetLibrary.registerWidget('fileupload', FileComponent);
  }
```
The fileupload is my add type and FileComponent is the type component

4.In your app module import your component and put it in "declarations" and  "entryComponents" similar following
```
declarations: [     
        FileComponent
    ],   
       entryComponents:[
         FileComponent
]
```

**Comment by neil-coutinho** [comment]
@qwe852147 do you have a working fiddle or sample code on your custom widget?
