### ISSUE TITLE
how to create more elements like H5 video capture

### ISSUE THREAD

**Issue by ericdai** [dschnelldavis/angular2-json-schema-form#35]
we want to setup mode elements like H5 video capture ,also we like a markdown editor like editor.md

**Comment by dschnelldavis** [comment]
Wrapping an existing markdown editor, like [SimpleMDE](https://simplemde.com/) for example, into a custom angular2-json-schema-form widget shouldn't be that difficult. It's specialized enough that it doesn't make sense for the core library, but it would be ideal as a separate add-on.

I think Video capture is outside the scope of this library though, even as an add-on. This library is only designed to handle data that can be put into a JSON object, and described by a JSON schema. And though markdown can be put into a text field, video data can't be comfortably converted into any JSON compatible format. So I doubt this library will ever be able to handle video, even with a custom widget. (Though I'd love for someone to prove me wrong. :-)

**Comment by agborkowski** [comment]
@dschnelldavis why not caputre element can be tract as widget as well like simplemde widget, upload field widget, so capture widget can be possible :)
