### ISSUE TITLE
support multi-columes

### ISSUE THREAD

**Issue by ericdai** [dschnelldavis/angular2-json-schema-form#36]

**Comment by ericdai** [comment]
like this

 http://www.protostrap.com/dashboard/designer/edit

**Comment by ericdai** [comment]
http://www.protostrap.com/dashboard/designer/edit

**Comment by dschnelldavis** [comment]
One example of how to do columns is in the demonstration playground, under Angular Schema Form / Bootstrap Grid, so it's technically already possible.

That's not the most elegant solution though, and I have been looking for better ways to handle form layouts. Long term, one of the most promising ideas appears to be the [JSON UI Schema](https://github.com/json-schema-org/json-schema-spec/issues/67), which this library will definitely implement once it's finished. Until then you can use the [form definition](https://github.com/json-schema-form/angular-schema-form/blob/master/docs/index.md#form-definitions) to control the layout,  as in the Bootstrap Grid example, even if it is a bit clunky.
