### ISSUE TITLE
Error when calling initializeControl from custom widget.

### ISSUE THREAD

**Issue by jurgenf** [dschnelldavis/angular2-json-schema-form#39]
When I call the method `initializeControl` on an instance of `JsonSchemaFormService` from within a custom widget component I get the following error:

`"Error in :0:0 caused by: Cannot read property 'hasOwnProperty' of null"`

I wonder if this has something to do with the injection of `JsonSchemaFormService` (I provide it inside my module because otherwise the service is unknown) or if this is otherwise broken.

The custom component is a copy of everything defined in `InputComponent` for testing so nothing custom is taking place at this point.

**Comment by dschnelldavis** [comment]
I don't know. If you post a repository with an example, I'll be glad to test it and give you a better answer.

**Comment by jurgenf** [comment]
Thank you for your response, as soon as I get back to working on the affected project again I will check if I can make a reproducible case.

**Comment by jurgenf** [comment]
After updating everything to the latest version the problem no longer seems to occur.
