### ISSUE TITLE
Change repo name to angular-json-schema-form

### ISSUE THREAD

**Issue by rjsteinert** [dschnelldavis/angular2-json-schema-form#40]
Angular2 is now just Angular. Pre Angular 2 is AngularJS.

**Comment by dschnelldavis** [comment]
I agree "Angular 2" no longer quite fits. Unfortunately, there is already an [angular-json-schema-form on NPM](https://www.npmjs.com/package/angular-json-schema-form), so if I want to use the same name on GitHub and NPM, I can't use that. Also, many libraries starting with "angular" are actually for AngularJS, not Angular 2 or 4, which can be confusing. So I've noticed that [several libraries are keeping the "2"](https://github.com/brillout/awesome-angular-components), which clearly communicates they are not for AngularJS, and seems like a good idea, even if the 2 is not strictly correct any more. When this library gets closer to production-ready I may change the name to ng-json-schema-form or ng-jsf or something similar, but while it's in alpha I'm going to leave the name as is.
