### ISSUE TITLE
Will update for Angular4??

### ISSUE THREAD

**Issue by qwe852147** [dschnelldavis/angular2-json-schema-form#41]
This angular2-json-schema-form using in Angular4 doesn't be build  .
This will be updated for Angular4?

**Comment by aitoribanez** [comment]
https://github.com/dschnelldavis/angular2-json-schema-form/pull/44

**Comment by dschnelldavis** [comment]
Finally updated. The new version (v0.4.0-alpha5 and above) is fully compatible with Angular 4. The latest version (v0.4.0-alpha7) installed from NPM has been tested and confirmed working with both the Angular 4 [quickstart seed](https://github.com/angular/quickstart) using SystenJS and [Angular CLI](https://cli.angular.io/) using Webpack.
