### ISSUE TITLE
Input can not type other language

### ISSUE THREAD

**Issue by qwe852147** [dschnelldavis/angular2-json-schema-form#43]
The text input can not type other language example chinese etc..

**Comment by jasminecjc** [comment]
Have you fixed this problem?

**Comment by qwe852147** [comment]
I change the following code (input) to (keydown) with custom widget
https://github.com/dschnelldavis/angular2-json-schema-form/blob/1a5bfee8744666d8504369ec9e6dfeb1c27f8ce1/src/lib/src/widget-library/input.component.ts#L44

**Comment by jasminecjc** [comment]
Do you have any code example of how to create custom widget?

**Comment by qwe852147** [comment]
You can see https://github.com/dschnelldavis/angular2-json-schema-form/issues/21 to try
