### ISSUE TITLE
Is angular2-json-schema-form AOT compatible?

### ISSUE THREAD

**Issue by pxanoop** [dschnelldavis/angular2-json-schema-form#46]
Getting error while implementing i18n and it seems libraries used in the application are not AOT compatible. Please let me know whether  angular2-json-schema-form is AOT compatible?

**Comment by dschnelldavis** [comment]
Yes angular2-json-schema-form is now AOT compatible.

It wasn't compatible when you posted this, but the latest version uses a completely overhauled build process, which should be fully AOT compatible.

**Comment by ujitha** [comment]
is angular4-json-schema-form is upgraded version of angular2-json-schema-form ? and Is angular4-json-schema-form AOT compatible?
