### ISSUE TITLE
Update operation: populate values

### ISSUE THREAD

**Issue by anikets43** [dschnelldavis/angular2-json-schema-form#47]
I have an use case where I'm using _angular2-json-schema-form_  to perform CRUD operation. I am using the schema to polpulate the form controls and then storing the values as a key-value pair(JSON) in the database. 
How do I pre-populate the values to the controls?
How to use [model] attribute with <json-schema-form>

Kudos for awesome library!!

Thanks

**Comment by dschnelldavis** [comment]
Apologies for taking so long to reply.

The "official" way to call angular2-json-schema-form is like this:
```html
<json-schema-form
  [schema]="yourJsonSchema"
  [layout]="yourJsonFormLayout"
  [data]="yourData"
  (onSubmit)="yourOnSubmitFn($event)">
</json-schema-form>
```
Here, the `data` input is for your default or previously submitted values, which will be used to pre-populate the the form controls.

However, angular2-json-schema-form also supports several alternative inputs, including `model`. So the following should also work:
```html
<json-schema-form
  [schema]="yourJsonSchema"
  [form]="yourAngularSchemaFormLayout"
  [model]="yourData"
  (onSubmit)="yourOnSubmitFn($event)">
</json-schema-form>
```
