### ISSUE TITLE
Unable to use 'condition'

### ISSUE THREAD

**Issue by PhilOldale** [dschnelldavis/angular2-json-schema-form#50]
I am using angular2-json-schema-form and trying to make use of the ‘condition’ functionality. In the playground examples for ASF there is the ‘Hack: Conditional Required’ example:

```
{
  "schema": {
    "type": "object",
    "properties": {
      "switch": {
        "title": "Spam me, please",
        "type": "boolean"
      },
      "email": {
        "title": "Email",
        "type": "string",
        "pattern": "^\\S+@\\S+$",
        "description": "Email will be used for evil."
      }
    },
    "required": [
      "switch"
    ]
  },
  "form": [
    {
      "type": "help",
      "helpvalue": "<p>Schema Form does not support oneOf (yet), but you can do a workaround and simulate certain scenarios with 'condition' and 'required'  (and/or 'readonly') in the form.</p>"
    },
    "switch",
    {
      "key": "email",
      "condition": "model.switch",
      "required": true
    },
    {
      "key": "email",
      "condition": "!model.switch"
    },
    {
      "type": "submit",
      "style": "btn-info",
      "title": "OK"
    }
  ]
}
```

I have found that both fields are displayed, and the value of ‘condition’ appears to have no effect?

![screenshot](https://cloud.githubusercontent.com/assets/8669904/26783501/7d26c96a-49f0-11e7-865f-eef882282554.jpg)

**Comment by agborkowski** [comment]
🍺

**Comment by germanamz** [comment]
This is because the function "isConditionallyShown" in "RootComponent" is not compiled right

Typescript:
```
isConditionallyShown(layoutItem: any): boolean {
    let result: boolean = true;
    if (this.data && hasOwn(layoutItem, 'condition')) {
      const model = this.data;

      /* tslint:disable */
      eval('result = ' + layoutItem.condition);
      /* tslint:enable */
    }
    return result;
  }
```

ES5 (build):
```
RootComponent.prototype.isConditionallyShown = function (layoutItem) {
        var /** @type {?} */ result = true;
        if (this.data && hasOwn(layoutItem, 'condition')) {
            eval('result = ' + layoutItem.condition);
            /* tslint:enable */
        }
        return result;
    };
```

A posible solution is to use "this.data.switch" to access the this scope of the "isConditionallyShown", this solution works but is not the prettiest.

**Comment by MonkeyDo** [comment]
Has this ever worked?
Reading the isConditionallyShown function it is not clear to me how eval is supposed to have access to the data context.
```const model = this.data;```is defined but never used, which probably explains why it is processed out upon compilation.

This seems to work for me work:
```
isConditionallyShown(layoutItem: any): boolean {
    let result: boolean = true;
    if (this.data && hasOwn(layoutItem, 'condition')) {
      const model = this.data;
      with(model){ // Give eval this.data as a context
          /* tslint:disable */
          eval('result = ' + layoutItem.condition);
          /* tslint:enable */
      }
    }
    return result;
  }
```

**Comment by MonkeyDo** [comment]
Ah, I see. Using the original code, my condition property must start with ```this.data``to reference the data context.

Good enough for me for now.

**Comment by dschnelldavis** [comment]
'condition' support has been added, and the 'Hack: Conditional Required' and similar examples should now work correctly.

**Comment by pdinesh80** [comment]
Condition works fine as from the example, have a question
Can i use condition on string fields instead of boolean and check for expression?
for example

{
  "schema": {
    "type": "object",
    "properties": {
      "text": {
        "title": "Spam me, please",
        "type": "string"
      },
      "email": {
        "title": "Email",
        "type": "string",
        "pattern": "^\\S+@\\S+$",
        "description": "Email will be used for evil."
      }
    },
    "required": [
      "switch"
    ]
  },
  "form": [
    {
      "type": "help",
      "helpvalue": "<p>Schema Form does not support oneOf (yet), but you can do a workaround and simulate certain scenarios with 'condition' and 'required'  (and/or 'readonly') in the form.</p>"
    },
    "switch",
    {
      "key": "email",
      **"condition": "model.text=='hello'",**
      "required": true
    },
    {
      "key": "email",
      **"condition": "model.text!='hello'",**
    },
    {
      "type": "submit",
      "style": "btn-info",
      "title": "OK"
    }
  ]
}

**Comment by sharanainapurapu** [comment]
I actually wanted to show the second item only when the user clicks on No. At the same time I want the value of the No to be false. I was trying with negation, It did working. I used the above example and was able to fix it. Thank you @pdinesh80 !!

Issue:
```
        { 
          "key": "isLastDateOver", 
          "title": "Is last date over?", 
          "type": "radios",
          "inline": true,
          "titleInline": true,
          "titleMap": {
            "true": "Yes",        
            "false": "No"
          }
        }, 
        { 
          "key": "lastDate",
          "type": "date",
          "title": "Last Date",
          "condition": "!model.isLastDateOver",
          "required": true  
        }
```

Solution:
```
        { 
          "key": "isLastDateOver", 
          "title": "Is last date over?", 
          "type": "radios",
          "inline": true,
          "titleInline": true,
          "titleMap": {
            "true": "Yes",        
            "false": "No"
          }
        }, 
        { 
          "key": "lastDate",
          "type": "date",
          "title": "Last Date",
          "condition": {
            "functionBody":"try { return !model.isLastDateOver } catch(e){return false}"
          } 
        }
```
