### ISSUE TITLE
NPM Module behaves different than lib version. Problems with Material Design and selected framework.

### ISSUE THREAD

**Issue by creadicted** [dschnelldavis/angular2-json-schema-form#54]
Hello!
If I use the npm installation as described in the documentation, the generated forms are not render correctly. I use material design and am not sure if it is because of the selected framework or if I missed something but the npm package also does not give access to a FrameworkLibraryService. 

`import {FrameworkLibraryService} from 'angular2-json-schema-form/src/framework-library';`
leads to: ` Can't resolve 'angular2-json-schema-form/src/framework-library'...`

the path referenced in the documentation is: 
`import { FrameworkLibraryService } from 'angular2-json-schema-form';`
but angular2-json-schema-form has no exported member 'FrameworkLibraryService'

also `[framework]='material-design'` or `[framework]='boostrap-3'` does not have any effect on the rendering. 

I tried out the `lib` version provided in the example app. There the rending works, but would definitely not be the preferred way of using the package.

**Comment by knehez** [comment]
In the template file that refer to the framework type, give the name of the framework you defined in the .ts file, then in the .ts file, put the 'material-design' as the value of the name. 
 .html:
<json-schema-form
[form]="questionSchema"
[framework]="frameworktype"
[loadExternalAssets]="true"
(onSubmit)="submitquestions($event)">

then in the class (.ts).
frameworktype='material-design'

**Comment by JKing-B16** [comment]
I actually had to take creadicted's method to get things to work. I copied the lib/ from the GIT source into my project and imported the from the ../../lib version in my app.module.ts. After that I was able to use selects without issue or any other changes to the code. Where as using the NPM version always produced a JavaScript error. The select would appear, but the selection couldn't be made.

**Comment by dschnelldavis** [comment]
Can you tell me if this is still an issue?

I've improved the Material Design compatibility and also made some additional improvements to the select control.  But I didn't have this problem initially, so I have no way to tell if it's been fixed or is still a problem.

Thanks.
