### ISSUE TITLE
Cannot import the module

### ISSUE THREAD

**Issue by manuelarte** [dschnelldavis/angular2-json-schema-form#58]
```
@NgModule({
    imports: [
        AppRoutingModule,
        FlexLayoutModule,
        BrowserModule,
        HttpModule,
        MaterialModule,
        JsonSchemaFormModule,
        ...
export class AppModule {
}
```

But, when I try to use it in another module

```
<json-schema-form
    [schema]="getJsonSchema()"
    (onSubmit)="yourOnSubmitFn($event)">
</json-schema-form>
```

I get the following error:

'json-schema-form' is not a known element:

If I import JsonSchemaFormModule in the module I want to use it, I get that BowerModule is imported twice.

**Comment by Thorski** [comment]
Are you using lazy-loading scheme?   
There is a problem with lazy-load, see
https://github.com/dschnelldavis/angular2-json-schema-form/issues/48

**Comment by manuelarte** [comment]
Yes, I am using lazy load

**Comment by Thorski** [comment]
If you edit the source file material-design-framework.module.ts
and comment out the import of the BrowserAnimationsModule 
then it works with lazy load for me.

**Comment by manuelarte** [comment]
Hi Thorski,

But, can you do that when you installed the package using npm?

**Comment by dschnelldavis** [comment]
BrowserAnimationsModule has been removed from the required imports. However, I haven't tested lazy-loading this library, so I don't know if that is working or not, though it is something I eventually want to officially support.

The lazy-loding is being tracked in #48 , so I'm closing this as a duplicate, and you can check there for future updates.
