### ISSUE TITLE
rsync npm step raisning error while installing

### ISSUE THREAD

**Issue by alimohammad** [dschnelldavis/angular2-json-schema-form#6]
Hi,

I tried exploring your library because I am also interested in something similar to what you are trying to do but was unable to explore it properly as the example project is not get installed properly on windows platform. It throws error at rsync step.

Can you put some documentation around that step so that I have a better understanding how rsync works as I do not have enough experience with rsync.

Is there any work around for rsync step.

I am also interested in contributing to this project as it seems very interesting and a good learning to step up in angular2 learning.

Looking forward to hear from you.

alimohammad2011@gmail.com

**Comment by dschnelldavis** [comment]
Sorry to take so long to reply.

OK - after investigating several options, I finally removed rsync entirely from the build process, and replaced it with [cpr](https://www.npmjs.com/package/cpr), which should be cross-platform.

Please clone the latest version, run `npm start` in your terminal to see if it compiles correctly, and let me know how it works.

If you're interested in contributing, please do—I'd love the help.

If you want to start small, you might try creating wrapper for a custom widget. If you look in /src/widgets/widget-library.service.ts, you'll find a list of "Recommended 3rd-party add-on widgets", which I've been meaning to create wrappers for. The Spectrum color picker or ACE code editor would probably be easy ones to start with (the ACE editor is already used in the playground, though without a wrapper).

Or if you're more interested in working on something else, just let me know.

**Comment by alimohammad** [comment]
Thanks a lot,

npm install and start worked like a charm 👍

**Comment by dschnelldavis** [comment]
Glad to hear it!
