### ISSUE TITLE
array inside array error

### ISSUE THREAD

**Issue by toni-h** [dschnelldavis/angular2-json-schema-form#64]
i got this kind of schema:
` "type": "object",
      "properties": {
        "queue": {
          "type": "object",
            "properties": {
                "host": { "type": "string" },
                "name": { "type": "string" }}},
         "protocolInfos": {
          "type": "array",
            "maxItems": 1,
            "items": {
          "type": "object",
        "properties": {
          "protocol": { "type": "string" },
          "host": { "type": "string" },
          "server": { "type": "string" },
          "communicator": { "type": "string" },
          "plcInfos": {
        "type": "array",
        "maxItems": 2,
         "items": {
          "type": "object",
        "properties": {
          "id": { "type": "string" },
          "host": { "type": "string" }}}}}}}       
        
      }`
![image](https://user-images.githubusercontent.com/18168409/28156373-286e2862-67bb-11e7-9326-0b620749824c.png)

when i try to add new plcInfo it gives me error:

`ERROR TypeError: this.getControlGroup(...).push is not a function
    at JsonSchemaFormService.webpackJsonp.../../../../angular2-json-schema-form/angular2-json-schema-form.es5.js.JsonSchemaFormService.addItem (angular2-json-schema-form.es5.js:23096)
    at AddReferenceComponent.webpackJsonp.../../../../angular2-json-schema-form/angular2-json-schema-form.es5.js.AddReferenceComponent.addItem (angular2-json-schema-form.es5.js:23216)`

but if i delete protocolInfos array and add it again i can also add new plcInfo array.
any idea wheres my problem?

thank you in advance
-Toni

**Comment by dschnelldavis** [comment]
This is fixed now. An earlier update broke the array support, but it has been fixed again.

You can check this in the [demonstration playground](https://angular2-json-schema-form.firebaseapp.com/) by pasting in the following schema:

```json
{
  "schema": {
    "type": "object",
    "properties": {
      "queue": {
        "type": "object",
        "properties": {
          "host": { "type": "string" },
          "name": { "type": "string" }
        }
      },
      "protocolInfos": {
        "type": "array",
        "maxItems": 1,
        "items": {
          "type": "object",
          "properties": {
            "protocol": { "type": "string" },
            "host": { "type": "string" },
            "server": { "type": "string" },
            "communicator": { "type": "string" },
            "plcInfos": {
              "type": "array",
              "maxItems": 2,
              "items": {
                "type": "object",
                "properties": {
                  "id": { "type": "string" },
                  "host": { "type": "string" }
                }
              }
            }
          }
        }
      }
    }
  }
}
```
