### ISSUE TITLE
Bug - input cursor changes position to the end of input when editing

### ISSUE THREAD

**Issue by george-oakling** [dschnelldavis/angular2-json-schema-form#69]
When editing whatever input in the middle of text, the focus changes position to the end of the input after typing first letter.

**Comment by george-oakling** [comment]
https://github.com/george-oakling/angular2-json-schema-form/commit/010dc9356f4c5ee800a995117f9f184a0754422a

**Comment by george-oakling** [comment]
Fix provided

**Comment by dschnelldavis** [comment]
@george-oakling , I merged your fix (thanks for providing it!), but it caused some other issues, so I had to take it back out.

This issue does sound serious, but unfortunately I'm not able to recreate it. Can you tell me more about the system you're using - OS / browser / etc. so I can see it for myself?

Thanks!
