### ISSUE TITLE
ERROR in Error encountered resolving symbol values statically - Angular CLI

### ISSUE THREAD

**Issue by alimohammad** [dschnelldavis/angular2-json-schema-form#7]
I just tried the library on an angular cli setup, and the moment I add angular2-json-schema-form into my app module or any other module, I am getting the above error. The log is as below:

**The issue is coming the moment I am adding **JsonSchemaFormModule.forRoot(),** in the import array of my module.**

ERROR in Error encountered resolving symbol values statically. Calling function 'JsonSchemaFormModule', function calls are not supported. Consider
replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in C:/Projects/sample-portal-old/src/app/app.module.ts, resolving symbol AppModule in C:/Projects/sample-portal-old/src/app/app.module.ts

My Setup:
angular-cli: 1.0.0-beta.24
node: 7.2.1
os: win32 x64
@angular/common: 2.4.1
@angular/compiler: 2.4.1
@angular/core: 2.4.1
@angular/forms: 2.4.1
@angular/http: 2.4.1
@angular/platform-browser: 2.4.1
@angular/platform-browser-dynamic: 2.4.1
@angular/router: 3.4.1
@angular/compiler-cli: 2.4.1

I did some research of my own about this issue and a lot of libraries are giving this issue.
Reference: 
https://github.com/angular/angular-cli/issues/3674#issuecomment-268618305
https://github.com/angular/angular-cli/issues/3707
https://github.com/auth0/angular2-jwt/issues/258

Most of the comments made me conclude that metadata need to be published with the library as well.

Since I am new to angular so could not look more deeper into this issue. Can you have a look onto this.

**Comment by empirefox** [comment]
Try again with src like `import { JsonSchemaFormModule } from 'angular2-json-schema-form/src'`.

**Comment by alimohammad** [comment]
@empirefox: It worked, thanks for the help. had to install lodash & @types/lodash after importing angular2-json-schema-form/src.

@dschnelldavis: you should update the document for the cli project, it will help others.

**Comment by dschnelldavis** [comment]
I think I've fixed this issue, but I'd like to make sure before I close it.

I moved @types/lodash to dependencies in package.json to automatically include it - which means you no longer have to separately import lodash or @types/lodash. So if you upgrade to the latest version from NPM (currently 0.3.0-alpha.23) you can uninstall lodash and @types/lodash (unless you're also using them for something else in your project), and it should still work.

I also added a separate section to the readme describing how to install with Angular CLI, explaining that you have to use  `import { JsonSchemaFormModule } from 'angular2-json-schema-form/src';`. Please take a look at the new readme and let me know if the new instructions are clear enough to enable future Angular CLI users to install without problems. As soon as you confirm they are, I'll close this.

Thanks!

**Comment by alimohammad** [comment]
@dschnelldavis The documentation looks great. I will update the npm package later since I am using lodash for other purposes as well.

**Comment by dschnelldavis** [comment]
Great. Thanks for the feedback.

**Comment by jh-code** [comment]
Upon further investigation, in order for it to be AoT compatible, all methods and properties must be declared public. http://stackoverflow.com/a/39379451

**Comment by dschnelldavis** [comment]
@jh - I have only a little experience with webpack, and almost none with AoT, but I would like this library to work with both.

Could you please post basic directions, or links for directions elsewhere, describing how to create a similar setup to the one you're using, so I can recreate the errors you got and then update the library to fix them?

Thanks.

**Comment by jh-code** [comment]
@dschnelldavis Basically to make it AoT compatible, your code needs to be statically analyzable. [Here is an article](https://medium.com/@isaacplmann/making-your-angular-2-library-statically-analyzable-for-aot-e1c6f3ebedd5#.w34aayqlg) explaining more about it and how to achieve it.

**Comment by dschnelldavis** [comment]
As of 0.4.0-alpha.11, I believe this issue has finally been fixed for good.

@jh-code Thank you for the article. It was tremendously helpful. It didn't cover everything, but it covered the basics well and gave me a good place to start for the rest.

This library's current build process uses Rollup for publishing to NPM, and Webpack for local testing with the demonstration playground, and both build systems appear to work fine. (As of version 0.4.0, we no longer use SystemJS at all.) I also did a series of tests running the NPM/Rollup version through the AoT compiler, and made updates until it compiled without errors.

If anyone still has this problem with version 0.4.0-alpha.11 or later let me know and I'll re-open this issue again.

**Comment by pdinesh80** [comment]
I see a similar issue in AOT build, I'm using the latest version of angular2-json-schema-form, Here is the error I see

Angular compilation done, starting webpack bundling.
Error: Metadata version mismatch for module /bld/workspace/test/node_modules/angular2-json-schema-form/angular2-json-schema-form.d.ts, found version 4, expected 3
    at StaticSymbolResolver.getModuleMetadata (/bld/workspace/test/node_modules/@angular/compiler/@angular/compiler.es5.js:25586:7)
    at StaticSymbolResolver._createSymbolsOf (/bld/workspace/test/node_modules/@angular/compiler/@angular/compiler.es5.js:25374:10)
    at StaticSymbolResolver.getSymbolsOf (/bld/workspace/test/node_modules/@angular/compiler/@angular/compiler.es5.js:25355:12)

**Comment by trivian118** [comment]
getting the same error version ^0.6.0-alpha.7

here is my package.json:
  "dependencies": {
    "@angular/animations": "^4.0.0",
    "@angular/cdk": "^5.0.4",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/material": "^5.0.4",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "body-parser": "^1.18.2",
    "core-js": "^2.4.1",
    "express": "^4.16.2",
    "morgan": "^1.9.0",
    "rxjs": "^5.1.0",
    "serve-favicon": "^2.4.5",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.1.0",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/language-service": "^4.0.0",
    "@types/jasmine": "2.5.45",
    "@types/node": "~6.0.60",
    "angular2-json-schema-form": "^0.6.0-alpha.7",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
