### ISSUE TITLE
this.options and this.widgetOption are undefined (null)

### ISSUE THREAD

**Issue by jmalkiewicz** [dschnelldavis/angular2-json-schema-form#75]
Hi,

I've tried to use the library however i get an error while initializing. 
The problem is that both members: this.options and this.widgetOptions are undefined (not set) and there occurs an error while setting this.options.title.

var VERSION = '4.17.4';

I've created a workaround, however i don't know if it fixes all cases:

    MaterialDesignFrameworkComponent.prototype.initializeControl = function () {
        if (this.layoutNode) {
            this.options = index_1(this.layoutNode.options);

// workaround start
			if (!this.options) {
				this.options = {};
			}
			if (!this.widgetOptions) {
	            this.widgetOptions = {};
			}
// workaround end
            
            this.widgetLayoutNode = Object.assign({}, this.layoutNode, { options: index_1(this.layoutNode.options) });
            this.widgetOptions = this.widgetLayoutNode.options;
            this.layoutPointer = this.jsf.getLayoutPointer(this);
            this.formControl = this.jsf.getControl(this);
            this.options.title = this.setTitle();
            if (this.options.minimum && this.options.maximum) {
                this.layoutNode.type = 'range';
.....

**Comment by gangasiddhi** [comment]
Am also facing same issue, could you please help me out.

**Comment by dschnelldavis** [comment]
This should be fixed in the latest version.
