### ISSUE TITLE
Nested arrays break when using custom layout

### ISSUE THREAD

**Issue by sconaghan** [dschnelldavis/angular2-json-schema-form#78]
I'm trying to create a form with a custom layout, but when adding layout options on top of using default data, the nested arrays all become the same length as the final item in the array. For example, if you take the flexbox layout example on [the playground](https://angular2-json-schema-form.firebaseapp.com/?set=ng2jsf&example=ng2jsf-flex-layout&framework=material-design) using the schema below, you will see that "Jane Doe" gets an extra phone number entry added with a value of "undefined" ("John has three phone numbers"). If you switch the order of the two data entries, "John Smith" will be missing a phone number entry ("Jane" has two phone numbers). However, if you take out the custom layout field, the data populates as you would expect.

Is this a bug, or is there a field or something I am missing?

`{
  "schema": {
    "type": "object",
    "properties": {
      "people": {
          "type": "array",
          "items": {
              "type": "object",
              "properties": {
                  "first_name": { "type": "string" },
                  "last_name": { "type": "string" },
                  "address": {
                    "type": "object",
                    "properties": {
                      "street_1": { "type": "string" },
                      "street_2": { "type": "string" }
                    }
                  },
                  "phone_numbers": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "number": { "type": "string" },
                        "type": {
                          "type": "string",
                          "enum": ["cell", "home", "work"]
                        }
                      },
                      "required": [ "number", "type" ]
                    }
                  }
              }
          }
      }
    }
  },
  "layout": [
    {
        "key": "people",
        "type": "array",
        "items": [
            "people[].first_name", 
            "people[].last_name",
            { "key": "people[].address.street_1", "title": "Address", "placeholder": "Street" },
            { "key": "people[].address.street_2", "notitle": true },
            { "key": "people[].phone_numbers",
              "type": "array",
              "items": [ {
                "type": "div",
                "displayFlex": true,
                "flex-direction": "row",
                "fxLayoutGap": "12px",
                "items": [
                  { "key": "people[].phone_numbers[].type", "flex": "1 1 50px", "notitle": true, "required": true },
                  { "key": "people[].phone_numbers[].number", "flex": "4 4 200px", "notitle": true }
                ]
              } ]
            }       
        ]
    }
  ],
  "data": {
    "people": [
        {
            "first_name": "Jane",
            "last_name": "Doe",
            "address": {
              "street_1": "123 Main St.",
              "street_2": null
            },
            "phone_numbers": [
              { "number": "702-123-4567", "type": "cell" },
              { "number": "702-987-6543", "type": "work" }
            ]
        },
        {
            "first_name": "John",
            "last_name": "Smith",
            "address": {
              "street_1": "456 South St.",
              "street_2": "Apt 3a"
            },
            "phone_numbers": [
              { "number": "703-222-2222", "type": "cell" },
              { "number": "703-111-1111", "type": "work" },
              { "number": "703-333-3333", "type": "home" }
            ]
        }  
    ]
  }
}
`

**Comment by dschnelldavis** [comment]
There's definitely a bug in the library.

I thought I'd fixed all the problems with arrays, but when I tried your schema, which looks pretty straightforward, it didn't work right for me either.

I'll look at it more tomorrow, and hopefully upload another fix soon.

Thanks for posting the example—it was very helpful.

**Comment by dschnelldavis** [comment]
Wow, that was a pain to fix—but worth it.

Nested arrays with custom layouts now work as of version 0.5.0-alpha.15.

**Comment by Thorski** [comment]
This appears to be broken again :(     Although it appears that  the nested arrays all become the same length as the SECOND item in the array, not the final one now.
