### ISSUE TITLE
Update material dependency from 2.0.0-beta.7 to 2.0.0-beta.10

### ISSUE THREAD

**Issue by Benjitos** [dschnelldavis/angular2-json-schema-form#83]
With version greater than 2.0.0-beta.7, forms with the material framework are not rendered correctly.
I suppose it's coming from material breaking changes on form. The framework-library should be modified. 
Extracts from material change logs:
> 	input: Inputs have a width of 200px by default (similar to native input elements). The width can be overridden by via the mat-form-field css class.
> 	**input: CSS classes have changed from mat-input-container- to mat-form-field-.**
> 	input: md-prefix and md-suffix are now mdPrefix and mdSuffix.
> 	**md-input-container has been renamed to md-form-field.**

[Material CHANGELOG.md](https://github.com/angular/material2/blob/master/CHANGELOG.md)	
	
By the way, thanks to @dschnelldavis for this great lib !  :-)

**Comment by dschnelldavis** [comment]
Done.

And thanks for the compliment. I think this is one of those projects where if I'd known in advance how much work it was going to be, I never would have done it. But now that I'm into it, I'm pretty happy with how it's evolving (even if it does still have a long way to go to get to a 1.0 release). :-)
