### ISSUE TITLE
Add optgroup to select widgets?

### ISSUE THREAD

**Issue by Thorski** [dschnelldavis/angular2-json-schema-form#87]
Is there a way?   I found in the code:

    // 'optgroup': TODO: automatically generated by select widgets (how?)
    // 'option': automatically generated by select widgets
    'textarea': TextareaComponent,

Anybody have a way to support this?

Thanks,

-- Thor

**Comment by dschnelldavis** [comment]
The current version (0.5.0-alpha.9) now supports this.

You can [see some examples here](https://angular2-json-schema-form.firebaseapp.com/?set=ng-jsf&example=ng-jsf-select-list-examples&framework=material-design).
