### ISSUE TITLE
Condition not working when the files are minified and uglified (Update: also, inside tabs)

### ISSUE THREAD

**Issue by iknowhow-sa** [dschnelldavis/angular2-json-schema-form#89]
Hello,
I discovered that the 'condition' property does not work after minification and uglification of files.
I'm using webpack for managing transpiling and deployment.

Searching through the code responsible for the conditions, I found that in 
`
/src/lib/src/widget-library/root.component.ts
`

you check the condition here:

```
isConditionallyShown(layoutItem: any): boolean {
    let result: boolean = true;
    if (this.data && hasOwn(layoutItem, 'condition')) {
      const model = this.data;

      /* tslint:disable */
      eval('result = ' + layoutItem.condition);
      /* tslint:enable */
    }
    return result;
  }
```

The only problem is that you first assign "this.data" to a const variable named model, and in your examples you use that named variable inside json schemas as the condition to be evaluated, eg
`...
"condition":"model.myCheckbox"
...`

The problem is that when the file is minified and uglified, this named variable will probable get renamed, therefore breaking the condition (console complains about model being undefined).

A very simple solution (more like a workaround) would be to use "this.data.myVariable" as a condition, which will always evaluate correctly, since object property names do not get minified.

Just a heads-up, thank you for your wonderful job :)

UPDATE: Conditions also don't work in elements inside tabs.

**Comment by stalsma** [comment]
I just checked w/a production build (ng build --prod), and it's working just fine.  

Maybe just an issue w/the npm build?

**Comment by dschnelldavis** [comment]
I don't have a good way to test this, and it appears to be working, so I'm going to close it.

If anyone still has this problem, please post an example I can use for testing and I'll be glad to re-open it and take a closer look.
