### ISSUE TITLE
Simple Array demo -> drag reorder slow

### ISSUE THREAD

**Issue by beeing** [dschnelldavis/angular2-json-schema-form#90]
Hi, great library! Been waiting for a ng2+ version of a json schema form.
Not sure you noticed that dragging the items in array to reorder is pretty slow.

I'm using latest Safari on macOS.

**Comment by dschnelldavis** [comment]
Thanks for pointing that out. I had a variation of [this problem](https://stackoverflow.com/questions/35756555/angular-2-drag-and-drop-directive-extremely-slow).

So I [moved the drag and drop listeners outside the Angular zone](https://github.com/dschnelldavis/angular2-json-schema-form/blob/master/src/lib/src/widget-library/orderable.directive.ts), and it's much faster now.
