### ISSUE TITLE
cannot find module 'angular2-json-schema-form'

### ISSUE THREAD

**Issue by miguelalarcos** [dschnelldavis/angular2-json-schema-form#92]
These are the steps to reproduce the issue:

* ng new my-forms
* cd my-forms
* npm install angular2-json-schema-form --save
* add line to my code:
```typescript    
import { JsonSchemaFormModule } from 'angular2-json-schema-form';
```

The IDE tells me that cannot find de module. If I try to build, it fails.

ng --version: 1.4.2

**Comment by dschnelldavis** [comment]
Oh crap! I had a problem with the build process yesterday, and the NPM versions of 0.5.0-alpha.5 and 0.5.0-alpha.6 are completely broken. Thank you for reporting this so promptly.

The immediate problem has been fixed as of NPM version 0.5.0-alpha.7.

In addition, as #66 points out, angular cli builds will still fail if required peer dependencies for [Angular Material](https://material.angular.io/) are not installed too. So I've added these to peerDependencies and updated the readme to reflect this in NPM version 0.5.0-alpha.8 .

Here are the new angular cli install steps, which I just tested as working:
```shell
ng new my-forms
cd my-forms
npm install angular2-json-schema-form --save
npm install @angular/cdk --save
npm install @angular/flex-layout --save
npm install @angular/material --save
```
Then add these lines to your code:
```javascript
import { FlexLayoutModule } from '@angular/flex-layout';
import { MaterialModule, MdDatepickerModule } from '@angular/material';
import { JsonSchemaFormModule } from 'angular2-json-schema-form';
```
Now run `npm run build` (or `ng build`), and it will work correctly.
